### ISSUE TITLE
Update all Boosters to booster-parent:4

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#11]
Addresses #9.

@cescoffier can run coordination, but all Booster owners can create issues/PRs and link here to ensure this is done.

@kenfinnigan @gytis

**Comment by gytis** [comment]
Updated Spring Boot boosters: https://github.com/openshiftio/booster-catalog/pull/26

**Comment by ALRubinger** [comment]
+1s that this is done for all Boosters under Swarm and Vert.x?  @cescoffier @kenfinnigan

**Comment by kenfinnigan** [comment]
+1, done

**Comment by cescoffier** [comment]
+1 done
