### ISSUE TITLE
Don't use Project Name for all things

### ISSUE THREAD

**Issue by kenfinnigan** [openshiftio/appdev-planning#12]
Currently the project name captured in the Launchpad UI is used for the project name, Maven artifactId and GH repo name.

In the OpenShift console this results in the booster being named `{projectName}-{projectName}` which is confusing.

Would be good to separately capture at least the artifactId of the generated booster, and maybe a GH repo name as well.

**Comment by ALRubinger** [comment]
Sounds like we might capture:
* GitHub repository name (required)
* OpenShift project name (required)
* Maven groupId (optional, default "io.openshift.booster")
* Maven artifactId (optional, default booster-$mission-$runtime)
* Maven version (optional, default 1.0.0-SNAPSHOT)
* Java package namespace (optional, default "io.openshift.booster")

**Comment by gastaldi** [comment]
Except the Java package namespace, which was removed from the addon (for now) all these fields are now available
