### ISSUE TITLE
Update all Booster's READMEs to point to appdev.openshift.io

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#14]
Docs is now available:

  http://appdev.openshift.io

For any instances where we have outdated content in booster READMEs, or READMEs pointing to the now-retired http://openshiftio-appdev-docs-appdev-documentation.tsrv.devshift.net, use the production link.

In the future we'll likely move to a system whereby new docs changes get built and trigger PRs into the appropriate Booster READMEs (as discussed in the Lisbon F2F), as this will give us versioned docs.

But for now, linking to the latest production/online documentation should do the trick, and we'll move away from stale content in READMEs.

This issue to track progress in all Boosters; will close out when verified by all owners this is done.

@cescoffier @kenfinnigan @gytis @cmoulliard @hbraun @starksm64

**Comment by gytis** [comment]
Spring Boot done.

**Comment by starksm64** [comment]
@gytis there is an outstanding PR to add more information about how the spring-boot-http-secured-booster should be checked out using the --recursive option:
https://github.com/snowdrop/spring-boot-http-secured-booster/pull/13

This is now in conflict with your change, so could you try to merge it in?

**Comment by starksm64** [comment]
There are pull requests for the vert.x and wildflyswarm secured rest boosters.

**Comment by gytis** [comment]
@starksm64 sorry I must have missed your PR. It's merged now.

**Comment by SlavoKrupa** [comment]
Vert.x Readmes are updated as well.

**Comment by gastaldi** [comment]
Readmes are updated in the launchpad-backend
