### ISSUE TITLE
Apply Look and Feel in the Keycloak Identity page

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/appdev-planning#17]
https://sso.openshift.io/auth/realms/osio-launch-prod/account/identity should be available in the frontend and should have the same Look and Feel as launch.openshift.io

**Comment by gastaldi** [comment]
Ideally we should have something like https://developers.redhat.com/auth/realms/rhd/account/identity

**Comment by edewit** [comment]
where is the source of https://sso.openshift.io/auth/realms/launchpad/account/identity so that we can fix this?

**Comment by ALRubinger** [comment]
Closing; we'll use the same realm as OSIO soon
