### ISSUE TITLE
Jenkins says "Agent to master security subsystem is currently off"

### ISSUE THREAD

**Issue by Ladicek** [openshiftio/appdev-planning#18]
I successfully deploy a booster of my selection to an OpenShift instance, and then go look at how the Jenkins pipeline progresses. The top bar in the Jenkins UI shows 1 warning: `Agent to master security subsystem is currently off`. As a user, this worries me a bit -- is my security compromised somehow?

Not on Minishift, obviously. But will this happen in prod as well?

(I did read https://wiki.jenkins-ci.org/display/JENKINS/Slave+To+Master+Access+Control and I think the slave/master separation should be enabled. Or is there a reason why we can't do that?)

**Comment by gastaldi** [comment]
Replaced with S2I Builder
