### ISSUE TITLE
Make Launchpad work with OpenShift Online

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#2]
Let's all focus on this as a matter of priority.  This issue can track issues in individual repos needed to accomplish this common goal.

Steps I've taken so far:

```
  Login to:

  https://tsrv.devshift.net:8443

Process template:

  https://raw.githubusercontent.com/openshiftio/launchpad-templates/master/openshift/launchpad-template.yaml

1) No GH Username
2) No GH password
3) Console URL: https://console.free-int.openshift.com
4) No OpenShift user name
5) No OpenShift password
6) KeyCloak URL: http://sso.prod-preview.openshift.io
7) KeyCloack Realm: fabric8
8) Launchpad Backend URL: http://launchpad-backend-$PROJECTNAME.tsrv.devshift.net (ie. $PROJECTNAME is "launchpad" if the OpenShift Project Name is "launchpad")
```

Result on "Deploy to OpenShift" button is an error, with log in the missioncontrol:

```
Caused by: java.lang.IllegalArgumentException: Invalid token.
	at io.openshift.appdev.missioncontrol.service.keycloak.impl.KeycloakServiceImpl.getToken(KeycloakServiceImpl.java:101)
	at io.openshift.appdev.missioncontrol.service.keycloak.impl.KeycloakServiceImpl.getGitHubIdentity(KeycloakServiceImpl.java:71)
	at io.openshift.appdev.missioncontrol.service.keycloak.impl.KeycloakServiceImpl$Proxy$_$$_WeldClientProxy.getGitHubIdentity(Unknown Source)
```

**Comment by quintesse** [comment]
@ALRubinger aren't `https://tsrv.devshift.net` and `https://console.free-int.openshift.com` different servers?

**Comment by ALRubinger** [comment]
@quintesse Yes; We'd put Launchpad on devshift and have it execute against the API on the OSO Free Integration Cluster.  Similarly we could even install Launchpad on Minishift locally and have it call out to OSO Free.

**Comment by quintesse** [comment]
@alr you get the error because the template is made for installation on a local OpenShift/minishift only.
If you look for the following lines:

          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_API_URL
            value: https://openshift.default.svc.cluster.local

and change the value to `https://console.free-int.openshift.com` things will work.

**Comment by quintesse** [comment]
Like discussed we could create a second template especially for the non-minishift situation where we would just change that section to:

          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_API_URL
            value: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL}
          - name: LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL
            value: ${LAUNCHPAD_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL}

Setting both the API_URL and the CONSOLE_URL to the same value that the user puts in the form when applying the template.

For the Minishift version we'll keep looking for a way to just "hard-code" the URL so we don't have to fill in any URL at all (if at all possible).

**Comment by quintesse** [comment]
Btw, once running the Jenkins build fails with:

```
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ demo ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
To build this project Maven 3.2.5 (or greater) is required. Please install it.
```

**Comment by ALRubinger** [comment]
@tako: RE: the build failing because of Maven, we're tracking that: https://issues.jboss.org/browse/OBST-111 (RHT only, sorry)

**Comment by ALRubinger** [comment]
@quintesse +1 on creating a second template for the non-Minishift version, so we can keep the Minishift one as trim as possible for users.  A bunch of duplication, but we can keep the two in sync I guess?  WDYT?

**Comment by quintesse** [comment]
With the new template this should work:

```
 1) No GH Username
 2) No GH password
 3) Local OpenShift API URL: https://tsrv.devshift.net:8443
 4) Target OpenShift Console URL: https://console.free-int.openshift.com
 5) No OpenShift user name
 6) No OpenShift password
 7) KeyCloak URL: http://sso.prod-preview.openshift.io
 8) KeyCloack Realm: fabric8
 9) Catalog Git Repository: https://github.com/openshiftio/booster-catalog.git
 10) Catalog Git Reference: master
 11) Catalog Index Period: 0
 12) Launchpad Backend URL: http://launchpad-backend-$PROJECTNAME.tsrv.devshift.net (ie. $PROJECTNAME is "launchpad" if the OpenShift Project Name is "launchpad")
```

but it doesn't :/

**Comment by edewit** [comment]
Definitely something wrong with the sso setup, when I go to `https://console.free-int.openshift.com` I get a `login with keycloak` button and when I logout I get a invalid redirect uri.

**Comment by edewit** [comment]
easier test to see if it works just put `http://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/github/token` into your browser and get the same message.

**Comment by ALRubinger** [comment]
Latest I am using:

```
Login to:

  https://tsrv.devshift.net:8443

Process template:

  https://raw.githubusercontent.com/openshiftio/launchpad-templates/master/openshift/launchpad-template.yaml

1) No GH Username
2) No GH password
3) API URL: https://api.free-int.openshift.com
3) Console URL: https://console.free-int.openshift.com
5) No OpenShift user name
6) No OpenShift password
7) KeyCloak URL: https://sso.prod-preview.openshift.io
8) KeyCloack Realm: fabric8
9) Backend URL: http://launchpad-backend-$PROJECTNAME.tsrv.devshift.net (ie. $PROJECTNAME is "launchpad" if the OpenShift Project Name is "launchpad") ie http://launchpad-backend-launchpad.tsrv.devshift.net
```

**Comment by gastaldi** [comment]
Blocked by https://issues.jboss.org/browse/OBST-197

**Comment by quintesse** [comment]
I now have 2 setups ways that should work:

Always using this template: https://raw.githubusercontent.com/openshiftio/launchpad-templates/master/openshift/launchpad-template.yaml

### Local Minishift, no Keycloak

1) Your GitHub user
2) Your GitHub token (see https://github.com/openshiftio/launchpad-missioncontrol)
3) API URL: leave default (`https://openshift.default.svc.cluster.local`)
3) Console URL: your local minishift console url
    - You can run `minishift console --url` to obtain this
5) OpenShift user: leave default (`developer`)
6) OpenShift password: leave default (`developer`)
7) KeyCloak URL: make empty
8) KeyCloack Realm: make empty
9) Backend URL: http://launchpad-backend-$PROJECTNAME.$HOSTNAMEORIP.nip.io
    - **$PROJECTNAME** is "launchpad" if the OpenShift Project Name is "launchpad", ie http://launchpad-backend-launchpad.tsrv.devshift.net
    - **$HOSTNAMEORIP** is the IP part of the Console URL, run `minishift console --url` and use only the IP

### Local Minishift, pushing to external OpenShift, , with Keycloak

1) GitHub user: leave empty
2) GitHub token: leave empty
3) API URL: https://api.free-int.openshift.com
3) Console URL: https://console.free-int.openshift.com
5) OpenShift user: make empty
6) OpenShift password: make empty
7) KeyCloak URL: leave default (`https://sso.prod-preview.openshift.io/auth`)
8) KeyCloack Realm: leave default (`fabric8`)
9) Backend URL: http://launchpad-backend-$PROJECTNAME.tsrv.devshift.net
    - **$PROJECTNAME** is "launchpad" if the OpenShift Project Name is "launchpad", ie http://launchpad-backend-launchpad.tsrv.devshift.net

**Comment by ALRubinger** [comment]
1) Log into https://console.free-int.openshift.com/console/.  It should take you through the Red Hat Developers login flow.  Clear any existing project you have in there.
2) Visit https://launchpad-frontend-launchpad.tsrv.devshift.net/wizard
3) Choose rest-http Mission and vertx Runtime
4) Launch on OpenShift
5) Post your findings here

**Comment by ALRubinger** [comment]
Reference: https://github.com/openshiftio/launchpad-missioncontrol/issues/232

**Comment by ALRubinger** [comment]
More reference: https://github.com/openshiftio/launchpad-jenkins-slave-dockerfile

**Comment by ALRubinger** [comment]
HTTP API Mission working for Vert.x, Swarm, Boot Boosters.  Enough to close this out.
