### ISSUE TITLE
http redirect to https

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#20]
launch.openshift.io should not support HTTP

Need to figure out how to enable this in OpenShift; currently we have no http routes for the frontend yet it still responds.

**Comment by gastaldi** [comment]
I think I found a solution, let me test locally before pushing

**Comment by gastaldi** [comment]
Fixed in https://github.com/openshiftio/launchpad-frontend/commit/a88620f5fbb224388472a8dfca33b416385e772f

**Comment by gastaldi** [comment]
That doesn't work as it should, the liveness probe doesn't perform correctly. Reopening

**Comment by gastaldi** [comment]
Fixed in https://github.com/openshiftio/launchpad-templates/commit/e0a4d37be63973578f46f281473fc82f8bb1276f
