### ISSUE TITLE
Add validation that the named GitHub repo doesn't already exist in the user's namespace

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#23]
Error prevention.

**Comment by gastaldi** [comment]
What do you mean? We already check if the github repository name doesn't already exist.

**Comment by ALRubinger** [comment]
![screenshot17](https://cloud.githubusercontent.com/assets/199891/26697313/81db3bc6-46df-11e7-828f-ede4c46bc6a8.png)
Great, thanks.
