### ISSUE TITLE
can openshift.io get a new version that works for spring boot apps?

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/appdev-planning#30]
we're using the git ref of `devtools-saas` for `LAUNCHPAD_BACKEND_CATALOG_GIT_REF` which is fine for vertx but the spring apps don't build (parent pom issues, deployment issues etc). 

Any chance of a new release that works & doesn't use parent poms or hit deployment problems?

**Comment by jstrachan** [comment]
@gastaldi any chance of a newer version please?

**Comment by gastaldi** [comment]
@jstrachan can you give it a shot with the "next" branch? That contains the released booster versions (not using master)

**Comment by jstrachan** [comment]
@gastaldi thanks the `next` branch worked a treat for the spring boot http booster!

though we've still an issue with the vertx tests failing if you edit the code https://github.com/openshiftio-vertx-boosters/vertx-http-booster/issues/2

**Comment by gastaldi** [comment]
@jstrachan do you guys still need the `devtools-saas` branch? Otherwise I'll remove it
