### ISSUE TITLE
Use productized Java S2I image 

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#36]
Move off the community versions provided by the Fabric8 community (and by default in the fabric8-maven-plugin) to use the image provided by Cloud Enablement.

**Comment by SlavoKrupa** [comment]
We can set it up in booster parent pom file just by adding property:
`fabric8.generator.from`, which should point to productized docker image.
Then we would need to:
* release new version of booster parent file
* update all booster with new parent version

**Comment by Ladicek** [comment]
I assume we want to do this unconditionally, even for boosters with community runtimes, right? I don't see a problem with that, but I can see why some would prefer to stay with Fabric8 Java S2I images with community runtimes and only use Red Hat productized Java S2I image with productized runtimes.

**Comment by ALRubinger** [comment]
RHT only: https://issues.jboss.org/projects/OBST/issues/OBST-87

**Comment by ALRubinger** [comment]
> I assume we want to do this unconditionally, even for boosters with community runtimes, right? I don't see a problem with that, but I can see why some would prefer to stay with Fabric8 Java S2I images with community runtimes and only use Red Hat productized Java S2I image with productized runtimes.

Yes, regardless of the runtime version, we'll use productized Java S2I.

Until we get a use case for why someone would need to use an alternate S2I base, let's just switch to the product one.
