### ISSUE TITLE
Support OSO Pro (Paid version)

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/appdev-planning#39]
With OSO Pro now out, we need to:

- Work with the DevTools group (@alexeykazakov) to set up a federated identity to this cluster in our shared OSIO security realm
- Add support to launch.openshift.io to choose where to target (OSO Starter or OSO Pro)

**Comment by rhoads-zach** [comment]
@ALRubinger please tag me as details emerge on this. Docs will need to be updated. Minimum changes i see so far:

* Update warning messages for certain boosters (e.g. SSO) related to running on OSO
* Provide links and/or callouts to OSO Pro details

FYI @inoxx03 @tradej @lavernw1

**Comment by ALRubinger** [comment]
Sure, @gastaldi can coordinate with ya

**Comment by gastaldi** [comment]
Just had a chat with @alexeykazakov in BlueJeans. Here is the action plan: 

- [ ] Add a new Identity Provider in our osio-launch-prod realm and test it  - George
- [ ]  Change the UI to allow the user to choose which OSIO instance to use  - George
- [ ] If things work out, then sync with Alexey to have the changes in our osio-launch-prod realm merged in the fabric8 realm (so we can deploy on us-east-1 AND pro)

**Comment by gastaldi** [comment]
Who can I bother to create a Client ID and Client Secret in the Openshift Pro cluster? I need an account in there too for testing purposes

**Comment by gastaldi** [comment]
Based on @quintesse 's suggestion, we'll add a `OPENSHIFT_CONFIG_FILE` env var containing a file in a JSON or YAML format containing the supported Openshift configurations (API and Console URLs)

**Comment by gastaldi** [comment]
Done, and templates were updated. The cluster configuration file contents is embedded in the openshift template and it is activated if the OPENSHIFT_API and CONSOLE URLs are not specified
