### ISSUE TITLE
Allow user selection of community or product runtimes

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#41]
RHT Internal: https://issues.jboss.org/projects/OBST/issues/OBST-301

**Comment by rhoads-zach** [comment]
@ALRubinger please tag me as more details emerge on this. We'll need to account for this in the docs in at least two ways:

1. UI changes to LOSIO and instructions for using it
2. Runtime descriptions and distinction between community and product runtimes.

FYI @inoxx03 @tradej @lavernw1

**Comment by quintesse** [comment]
https://github.com/openshiftio/launchpad-frontend/issues/146
https://github.com/openshiftio/launchpad-addon/issues/34
https://github.com/openshiftio/launchpad-backend/issues/58

**Comment by ALRubinger** [comment]
Status on this overarching issue?  Work done in Launch but needs work done in Catalog or by product teams?

**Comment by quintesse** [comment]
All the work on our side is done. It's up to the product teams to adjust their boosters.
(Should I close this issue leaving the OBST issue while we track and prod the product teams?)

**Comment by rdruss** [comment]
@quintesse, I think your work on this issue is done and this can be closed.  I've seen it working in action.  :-)

**Comment by quintesse** [comment]
Yup, you're right. Closing.
