### ISSUE TITLE
Move to OSIO security realm

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#42]

**Comment by rhoads-zach** [comment]
@ALRubinger please tag me as details emerge on this. We'll need to update the docs for this. Changes i can see so far:

* Update details and instructions for users authenticating to OSIO

FYI @inoxx03 @tradej @lavernw1

**Comment by gastaldi** [comment]
https://github.com/openshiftio/appdev-planning/issues/26 is related to this

**Comment by gastaldi** [comment]
This is something that will probably be a blocker. I tested the authentication in http://launchpad-nginx-launchpad-production.09b5.dsaas.openshiftapps.com and I get the message: `user ggastald-osio cannot create more than 1 project(s).`. 

Logging in my https://console.starter-us-east-2.openshift.com/console/ account, I see this: 

![screenshot from 2017-08-08 15-17-28](https://user-images.githubusercontent.com/54133/29087562-bf25bcb6-7c4c-11e7-83d4-106e4b4ae1e4.png)

Those projects were created when I logged into openshift.io, thus consuming my available quota.

**Comment by gastaldi** [comment]
After talking with Aslak,in the openshiftio-saas channel (https://chat.openshift.io/developers/pl/5u8khtyjkpgjjgygjyey1pqsuw) he mentioned that we'd need to deploy the booster in an existing project, therefore we need to change the UI (and Mission Control) to support that.

**Comment by gastaldi** [comment]
Created an issue: https://github.com/openshiftio/appdev-planning/issues/50

**Comment by gastaldi** [comment]
We'll move back to our original realm and add all the starter clusters
