### ISSUE TITLE
Frontend is Borked on Minishift 

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#5]
To repro:

1) Follow instructions to install Launchpad on Minishift
2) Visit frontend
3) Loading...

Blocker for all doing Minishift development

cc: @starksm64

**Comment by gastaldi** [comment]
* Go to Applications -> Deployments and choose the launchpad-frontend deployment
* Click the Environment tab
* Remove LAUNCHPAD_KEYCLOAK_URL and LAUNCHPAD_KEYCLOAK_REALM attributes
* Click Save
* Wait
...
* Profit

**Comment by quintesse** [comment]
It works @ALRubinger, you just need slightly different instructions than before.
As @gastaldi mentions if you want to set things up *without* Keycloak support you now *must* clear those settings in the template form. It's the way the frontend detects it shouldn't try to authenticate.

**Comment by quintesse** [comment]
See here for up-to-date instructions (as of right now): https://github.com/openshiftio/appdev-planning/issues/2#issuecomment-292496920

**Comment by kenfinnigan** [comment]
This is resolved right?

**Comment by starksm64** [comment]
It is if you follow the latest instructions. The main thins that cause problems are not clearing the KEYCLOAK related fields and errors in the Backend URL.

**Comment by quintesse** [comment]
Should be resolved yes. Closing.
