### ISSUE TITLE
Rebrand LOSIO to developers.redhat.com

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#52]
To be coordinated with Cat Robson and James Cobb

**Comment by catrobson** [comment]
Overall design:
![launch_homepage_aug10-2017](https://user-images.githubusercontent.com/3739227/29583288-9e6a7fa0-874d-11e7-9e18-37abfd36a90e.jpg)

@ALRubinger I think we need content reviewed and agreed upon under "Launch".

@edewit 
Logo: http://design.jboss.org/redhatdeveloper/rhdp_brand/logo/images/RHDP_logo_RGB_reverse_500px.png
Background image:  Let's get James Cobb to provide a real version, mine is pretty hacked up.  I'll send an e-mail.

**Comment by gastaldi** [comment]
@edewit the Launch Your Project button looks a bit different from the overall design above, is that correct?

**Comment by gastaldi** [comment]
Link for reference purposes: https://launch.prod-preview.openshift.io/wizard

**Comment by edewit** [comment]
@gastaldi yes that is correct the image here is an initial design. I've gotten an updated one by email the reason it's white now is because it contrasts better
