### ISSUE TITLE
Change launcher flow to start with selecting runtime

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-planning#58]
In the F2F last week, the question was posed as to whether the Launch flow could change to allow selection of runtime first.  Thinking through how a typical developer would engage with Launch, more than likely they already know what runtime they are interested in and would like to see the set of missions available for their runtime.  The flow is a bit counter to this.  An interesting side effect could be that this helps in allowing runtime specific missions as missions would be "pre-filtered" by the selection of runtime.

**Comment by gastaldi** [comment]
https://github.com/openshiftio/launchpad-addon/issues/26
