### ISSUE TITLE
Update Jenkinsfiles in all Boosters to use node "launchpad-maven"

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#6]
https://issues.jboss.org/browse/OBST-111
https://github.com/openshiftio/launchpad-missioncontrol/issues/217

We need to use a dependable build environment, one we create and control.  The default "maven" one provisioned by OpenShift will vary depending upon OSO Free, Minishift, etc.  Ours is an explicit ImageStream we can lock down so no matter which OpenShift instance you're using, you get the same Jenkins Slave image.

**Comment by ALRubinger** [comment]
@kenfinnigan @gytis @cescoffier Can I have +1s that this has been done for all Jenkinsfiles in the Boosters?  If so we can close. :)

**Comment by kenfinnigan** [comment]
+1 from WF Swarm

**Comment by gytis** [comment]
+1 for the Spring Boot (HTTP and CRUD)

**Comment by cescoffier** [comment]
+1 for vert.x
