### ISSUE TITLE
Refactor Mission Control for re-use

### ISSUE THREAD

**Issue by quintesse** [openshiftio/appdev-planning#66]
The idea is to:

 1. Move the "web" part of Mission Control to the backend, which means:
    1. Move the code
    2. Integrate with the backend
    3. Update any code, configuration and OpenShift templates that expects to talk to mission control to now talk to the backend
 2. Merge OSIO's "launch" code into ours in Mission Control
 3. Make OSIO's addon use Mission Control

**Comment by quintesse** [comment]
Right now step 1 is being developed in the following branches: https://github.com/fabric8-launch/launchpad-backend/tree/accept-web-from-missioncontrol and https://github.com/fabric8-launch/launchpad-missioncontrol/tree/move-web-to-backend

**Comment by gastaldi** [comment]
Merged into https://github.com/fabric8-launch/launcher-backend

**Comment by gastaldi** [comment]
These steps are still missing: 

2. Merge OSIO's "launch" code into ours in Mission Control
3. Make OSIO's addon use Mission Control

**Comment by gastaldi** [comment]
Step #2 seems done. We're working on bringing the OSIO to the same repository and refactoring to consume the mission control services

**Comment by gastaldi** [comment]
Opened https://github.com/openshiftio/openshift.io/issues/1499 to deal with the OSIO addon refactoring. Closing this now
