### ISSUE TITLE
Merge launchpad-backend with fabric8-backend

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/appdev-planning#69]
The backend is a REST wrapper for the Forge addons. The idea is to merge the backends available in https://github.com/fabric8-launch/launchpad-backend and https://github.com/fabric8io/generator-backend to have a single codebase.

**Comment by quintesse** [comment]
@gastaldi will you at least wait with this until I'm done with the other changes? I'm afraid the merging might be somewhat difficult otherwise.

**Comment by gastaldi** [comment]
Of course, we'll only start working on this after https://github.com/openshiftio/appdev-planning/issues/66 is done

**Comment by gastaldi** [comment]
Both codebases were merged in https://github.com/fabric8-launch/launcher-backend
