### ISSUE TITLE
appdev.openshift.io SSL Cert expired

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#71]
As reported by @jasonmadigan

<img width="1212" alt="ssl-expired" src="https://user-images.githubusercontent.com/199891/32839383-3ca1c968-c9e2-11e7-8ac4-2d2e250a626c.png">

**Comment by gastaldi** [comment]
Issue opened for our SD team: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/796.

Closing now
