### ISSUE TITLE
Refit application to proxy instead of redirect

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#72]
Our resources are set to load under the root `/` instead of `/launch`, where they'll be under `developers.redhat.com/launch`.  

Let's have our root `index.html` redirect to `/launch/index.html` and serve the application from there.

Instructions to test staging site:

1. From a terminal, run: `host developers.redhat.com.edgekey-staging.net`
(this returns 23.200.241.248 for me at the moment, but these are ephemeral and can change)

2. Add a line at the bottom of your /etc/hosts file with the IP you just grabbed:
`23.200.241.248 developers.redhat.com`

3. Confirm you are now hitting the stage environment by verifying the X-Akamai-Staging header is present: `curl -I https://developers.redhat.com/`
```
$ curl -I https://developers.redhat.com/
HTTP/1.1 200 OK
Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips
Last-Modified: Thu, 28 Sep 2017 15:34:23 GMT
ETag: "c9d5-55a41a4835dc0"
Accept-Ranges: bytes
Content-Length: 51669
Cache-Control: max-age=1800, public
Expires: Thu, 28 Sep 2017 16:42:51 GMT
Content-Type: text/html; charset=UTF-8
Date: Thu, 28 Sep 2017 16:14:26 GMT
Connection: keep-alive
X-Akamai-Staging: ESSL
```

4. Restart your browser and browse to `https://developers.redhat.com`

**Comment by edewit** [comment]
following the steps above I still get a redirect to `https://launch.openshift.io/` when visiting `http://developers.redhat.com/launch`

**Comment by gastaldi** [comment]
@edewit have you followed the above instructions?

**Comment by edewit** [comment]
yes

**Comment by gastaldi** [comment]
You're right. I get the same behavior. Replying to the email
